### ISSUE TITLE
How to run analysis pipeline from console 

### ISSUE THREAD

**Issue by dridk** [norling/metlab#10]
There is no documentation to explain how to run the analysis pipeline from bash terminal. 
Could you explain ?

**Comment by HadrienG** [comment]
Hi,

Unfortunately, at the moment only the read simulation module can be run at the command-line. The analysis pipeline has to be used from the GUI.

We're planning a version 2 for (hopefully!) the end of the year with an improved GUI, more softwares options and a command-line interface.

Thank you for your interest!

**Comment by dridk** [comment]
I successed by extracting command line from the sqlite database and create my own pipeline. I m doing a Snakefile pipeline. I will share it with you . 
I suggest you to use Qt5 for the user interface. And use Dockers or LXD to create an image.
