### ISSUE TITLE
install_dependencies.sh checks for printseq-lite not printseq-lite.pl

### ISSUE THREAD

**Issue by EricDeveaud** [norling/metlab#11]
Hello, 

install dependencies checks for printseq-lite while installed binarie from prontseq-lite is called printseq-lite.pl so it systematicaly install printseq-lite even if it already available from user path 

and pipeline.json use correct name: 
```
bigmess:/tmp/metlab > grep prinseq-lite pipeline.json                      
         "name":"prinseq-lite",
         "command":"<prinseq-lite.pl> -fastq <reads> [-fastq2 <paired reads>] -min_qual_mean %(min_qual)s -ns_max_p %(ns_max)s -derep %(derep)s -trim_qual_right %(trim_qual_right)s -out_format %(format)s -out_good %(out_good)s -out_bad %(out_bad)s [-graph_data %(graph_data)s]",
```

**Comment by HadrienG** [comment]
Thanks for reporting the issue! I've modified install_dependencies.sh to correctly check for prinseq.
