### ISSUE TITLE
Kraken compilation failing on OSX

### ISSUE THREAD

**Issue by HadrienG** [norling/metlab#3]
Kraken fails to build on OSX with the following error: 

    g++ -Wall -fopenmp -O3 -c krakendb.cpp
    clang: error: unsupported option '-fopenmp'
    Makefile:29: recipe for target 'krakendb.o' failed
    make: *** [krakendb.o] Error 1

**Comment by norling** [comment]
This occurs when using the native compiler - I'll try to update the install script to be better at using the downloaded GCC.
